# ===== SQLite Database =====
spring.datasource.url=jdbc:sqlite:veterinary_clinic.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# ===== JPA / Hibernate =====
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ===== Swagger UI =====
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# ===== Serwer =====
server.port=8080

# ===== Swagger UI =====
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# ===== Dane startowe =====
spring.sql.init.mode=always

